"""empty message

Revision ID: 70add9e56c16
Revises: 5ab344697914
Create Date: 2022-08-12 17:19:19.032440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70add9e56c16'
down_revision = '5ab344697914'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('seeking_talent', sa.Boolean(), nullable=False))
    op.add_column('venue', sa.Column('seeking_venue', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venue', 'seeking_venue')
    op.drop_column('artist', 'seeking_talent')
    # ### end Alembic commands ###
